
import { Card, Tile } from './types';

import avatar01 from './assets/avatars/avatar_01.png';
import avatar02 from './assets/avatars/avatar_02.png';
import avatar03 from './assets/avatars/avatar_03.png';
import avatar04 from './assets/avatars/avatar_04.png';
import avatar05 from './assets/avatars/avatar_05.png';
import avatar06 from './assets/avatars/avatar_06.png';
import avatar07 from './assets/avatars/avatar_07.png';
import avatar08 from './assets/avatars/avatar_08.png';
import avatar09 from './assets/avatars/avatar_09.png';
import avatar10 from './assets/avatars/avatar_10.png';

export const ROUTE_LENGTH = 12;
export const HOSPITAL_COST_MULTIPLIER = 1000;
export const pColors = ["#f1c40f", "#3b82f6", "#ef4444", "#22c55e", "#d946ef", "#06b6d4", "#ec4899", "#8b5cf6"];
// Using imported image paths for avatars.
export const pIcons = [avatar01, avatar02, avatar03, avatar04, avatar05, avatar06, avatar07, avatar08, avatar09, avatar10];

export const motivationalQuotes: { text: string; author: string; book: string; }[] = [
    // Vive al Cien
    { text: "¡Comienza hoy y vive tu vida al cien!", author: "JC", book: "Vive al Cien" },
    { text: "Vivir la vida al máximo no es un destino, es un camino.", author: "JC", book: "Vive al Cien" },
    { text: "El tiempo es limitado, no lo desperdicies viviendo la vida de otro.", author: "JC", book: "Vive al Cien" },
    { text: "La vida es una colección de momentos vividos con intención y propósito.", author: "JC", book: "Vive al Cien" },
    { text: "La verdadera paz es la capacidad de enfrentar los desafíos con valentía.", author: "JC", book: "Vive al Cien" },
    { text: "La vida más plena es aquella que se vive con un toque de locura.", author: "JC", book: "Vive al Cien" },
    { text: "Al otro lado del miedo se encuentra la libertad y la confianza.", author: "JC", book: "Vive al Cien" },
    { text: "La aventura no solo está en el destino, sino en cada paso del camino.", author: "JC", book: "Vive al Cien" },
    { text: "Cada aventura tiene el poder de transformar nuestra vida.", author: "JC", book: "Vive al Cien" },
    { text: "La vida comienza al final de tu zona de confort.", author: "JC", book: "Vive al Cien" },
    { text: "Cada final es simplemente el comienzo de algo nuevo.", author: "JC", book: "Vive al Cien" },
    { text: "¿Qué huella quieres dejar en el mundo?", author: "JC", book: "Vive al Cien" },
    { text: "La locura es la chispa que nos impulsa a soñar en grande.", author: "JC", book: "Vive al Cien" },
    { text: "Construir un legado es vivir de manera que tus acciones resuenen más allá del tiempo.", author: "JC", book: "Vive al Cien" },
    { text: "El verdadero éxito no está en los logros, sino en la huella positiva que dejamos.", author: "JC", book: "Vive al Cien" },
    { text: "La verdadera libertad implica liberarnos de las cadenas invisibles que nos atan.", author: "JC", book: "Vive al Cien" },
    { text: "Vivir con libertad es abrazar nuestras posibilidades con valentía y curiosidad.", author: "JC", book: "Vive al Cien" },
    { text: "Un legado no es solo lo que logramos, sino cómo impactamos a quienes nos rodean.", author: "JC", book: "Vive al Cien" },
    { text: "Cada acción cuenta, cada decisión importa.", author: "JC", book: "Vive al Cien" },
    { text: "Liderar es como ser el faro en una tormenta: iluminar el camino y ofrecer esperanza.", author: "JC", book: "Vive al Cien" },
    { text: "La vida no es una serie de pasos predecibles, sino una aventura vibrante.", author: "JC", book: "Vive al Cien" },
    { text: "El verdadero descubrimiento está en los giros inesperados y en explorar lo desconocido.", author: "JC", book: "Vive al Cien" },
    { text: "La verdadera transformación ocurre cuando aplicamos las ideas en nuestro día a día.", author: "JC", book: "Vive al Cien" },
    { text: "Cada amanecer es una página en blanco, una nueva oportunidad para escribir tu historia.", author: "JC", book: "Vive al Cien" },

    // AÚN
    { text: "Hay palabras que actúan como anclas y otras que funcionan como alas.", author: "JC", book: "AÚN" },
    { text: "El 'aún' es una grieta en el muro de lo imposible.", author: "JC", book: "AÚN" },
    { text: "La semilla crece donde nadie la ve. En lo oscuro.", author: "JC", book: "AÚN" },
    { text: "Los telones no caen, descansan. Un descanso no es un funeral. Es un 'aún'.", author: "JC", book: "AÚN" },
    { text: "No estás obligado a triunfar. Estás invitado a ser fiel.", author: "JC", book: "AÚN" },
    { text: "Ser fiel es aprender a decir 'aún' sin convertirlo en excusa.", author: "JC", book: "AÚN" },
    { text: "La única manera de no ahogarse es convertirse en orilla de otro.", author: "JC", book: "AÚN" },
    { text: "Una cicatriz no es una debilidad. Es la prueba de que sanaste.", author: "JC", book: "AÚN" },
    { text: "Tu grieta no es tu vergüenza. Es tu historia. Es tu medalla.", author: "JC", book: "AÚN" },
    { text: "Tu cuerpo no es una herramienta. Es tu compañero.", author: "JC", book: "AÚN" },
    { text: "La ruina no es un destino. Es un pasaje.", author: "JC", book: "AÚN" },
    { text: "El objetivo no es el puente, es cruzar al otro lado.", author: "JC", book: "AÚN" },
    { text: "El 'aún' es la bisagra que abre la puerta del futuro.", author: "JC", book: "AÚN" },
    { text: "El crecimiento más importante es invisible.", author: "JC", book: "AÚN" },
    { text: "Tu trabajo no es presenciar la cosecha. Tu trabajo es ser fiel a la siembra.", author: "JC", book: "AÚN" },
    { text: "Estar perdido es el prerrequisito para el verdadero descubrimiento.", author: "JC", book: "AÚN" },
    { text: "Nadie ha descubierto un nuevo continente siguiendo un mapa viejo.", author: "JC", book: "AÚN" },
    { text: "La palabra 'aún' es la brújula que emerge cuando el mapa se vuelve inútil.", author: "JC", book: "AÚN" },
    { text: "El Logro no es un destino, sino la sinfonía que suena cuando todas tus pasiones tocan en armonía.", author: "JC", book: "AÚN" },
    { text: "Tu historia no ha terminado. Aún.", author: "JC", book: "AÚN" },
    { text: "No estás roto. Simplemente, tu reparación con oro no ha terminado.", author: "JC", book: "AÚN" },
    { text: "El 'aún' nos devuelve al ritmo natural del crecimiento.", author: "JC", book: "AÚN" },
    { text: "Tu potencial no tiene fecha de caducidad.", author: "JC", book: "AÚN" },
    { text: "Lo que aún no sucede ya te está buscando.", author: "JC", book: "AÚN" },
    { text: "A oscuras también se escuchan las verdades que no se ven.", author: "JC", book: "AÚN" },
    { text: "Confundes el final de una carrera con el final de la carrera.", author: "JC", book: "AÚN" },
    { text: "La verdadera riqueza de la vida se encuentra en las conexiones que formamos.", author: "JC", book: "AÚN" },
    { text: "No son las cosas materiales las que nos llenan de felicidad, sino las personas con las que compartimos nuestro viaje.", author: "JC", book: "AÚN" },
    { text: "El único riesgo que debería aterrarte es el de no hacer el trabajo para el que naciste.", author: "JC", book: "AÚN" },
];

export const routeCompletionMessages = [
    "¡Lo lograste! Has trascendido esta etapa y tu crecimiento es evidente.",
    "Avanzaste en esta ruta de la vida. Tu sabiduría se expande.",
    "¡Felicidades! Un nuevo nivel de consciencia desbloqueado.",
    "Has completado este camino con éxito. Llevas contigo grandes aprendizajes.",
    "Tu perseverancia ha dado frutos. Esta experiencia te hace más fuerte.",
    "Cierras un ciclo y abres la puerta a nuevas oportunidades.",
    "¡Misión cumplida! Tu evolución en esta área es inspiradora."
];

export const mazoReto: Card[] = [
    { t: "Imita a alguien famoso (real o inventado). Si alguien lo adivina.", r: { happy: 2 }, i: "🎭", c: "bg-blue-100" },
    { t: "Haz reír a un jugador en 15 segundos. Si lo logras.", r: { happy: 1 }, i: "😂", c: "bg-blue-100" },
    { t: "Comienza a decir palabras con 'A'. Si logras decir 25 sin repetir.", r: { money: 2000 }, i: "🅰️", c: "bg-blue-100" },
    { t: "Baila 20 segundos como si ganaras un premio. Si el grupo aplaude.", r: { health: 1, happy: 1 }, i: "💃", c: "bg-blue-100" },
    { t: "Canta todo lo que digas hasta tu siguiente turno. Si lo haces.", r: { happy: 1 }, i: "🎵", c: "bg-blue-100" },
    { t: "Repite un trabalenguas que te diga otro jugador. Si lo logras.", r: { money: 1000 }, i: "🗣️", c: "bg-blue-100" },
    { t: "Haz una selfie con todos, si alguno no sonríe te paga 1 Felicidad.", r: { happy: 2 }, i: "📸", c: "bg-blue-100" },
    { t: "Piensa en algo verde y da 3 pistas. Si nadie lo adivina.", r: { money: 1000 }, i: "🟢", c: "bg-blue-100" },
    { t: "Haz una escena dramática. Si te aplauden.", r: { health: 2 }, i: "🎭", c: "bg-blue-100" },
    { t: "Inventa y di un producto ridículo pero útil. Si les gusta a la mitad.", r: { money: 3000 }, i: "💡", c: "bg-blue-100" },
    { t: "Tira un dado. Si es impar, todos te dan $1,000.", r: { money: 1000 }, i: "🎲", c: "bg-blue-100" },
    { t: "Simula una llamada a un manicomio. Si aguantan 30 seg sin reír.", r: { money: 2000 }, i: "📞", c: "bg-blue-100" },
    { t: "Crea un jingle de este juego. Si alguien más canta contigo.", r: { happy: 2 }, i: "🎶", c: "bg-blue-100" },
    { t: "Actúa como un animal que hace algo raro. Si haces reír.", r: { happy: 2 }, i: "🦄", c: "bg-blue-100" },
    { t: "Simula pedir una pizza de insectos y sé específico. Si lo haces bien.", r: { happy: 2 }, i: "🍕", c: "bg-blue-100" },
    { t: "Imita a un alien que da consejos sabios sobre uñas. Si alguien ríe.", r: { happy: 1 }, i: "👽", c: "bg-blue-100" },
    { t: "Solo sonríe 30 segundos sin parar.", r: { health: 2, happy: 2 }, i: "😁", c: "bg-blue-100" },
    { t: "Di 3 cosas que harías si fueras invisible. Si sorprendes.", r: { money: 3000 }, i: "👻", c: "bg-blue-100" },
    { t: "Inventa anuncio de bebida sabor pollo con plumas. Si alguien ríe.", r: { money: 500 }, i: "🍗", c: "bg-blue-100" },
    { t: "Pide silencio, si logras que el grupo calle 10 seg.", r: { happy: 1 }, i: "🤫", c: "bg-blue-100" },
    { t: "Di 5 tipos de frutas sin repetir en 5 segundos. Si lo logras.", r: { money: 1000 }, i: "🍎", c: "bg-blue-100" },
    { t: "El jugador a tu izquierda elige una canción y debes tararearla. Si alguien la adivina.", r: { happy: 2 }, i: "🎵", c: "bg-blue-100" },
    { t: "Duelo de miradas con el jugador de enfrente. El primero que parpadee le da $1,000 al otro.", r: { money: 1000 }, i: "👀", c: "bg-blue-100" },
    { t: "Párate y da 5 vueltas sobre ti mismo. Si no te caes.", r: { health: 1, happy: 1 }, i: "🌀", c: "bg-blue-100" },
    { t: "Cuenta un chiste. Si nadie se ríe, pierdes 1 de Felicidad. Si alguien ríe.", r: { happy: 2 }, i: "🃏", c: "bg-blue-100" },
    { t: "Nombra 3 países que empiecen por la letra 'M' en 5 segundos.", r: { money: 1000 }, i: "🌍", c: "bg-blue-100" },
    { t: "Toca la punta de tus pies sin doblar las rodillas. Si lo logras.", r: { health: 2 }, i: "🦶", c: "bg-blue-100" },
    { t: "Haz una mueca graciosa y manténla mientras los demás intentan no reír 10 seg.", r: { happy: 2 }, i: "😜", c: "bg-blue-100" },
    { t: "Di el abecedario al revés empezando desde la J. Si lo logras.", r: { money: 1000 }, i: "🔤", c: "bg-blue-100" },
    { t: "Elige a un jugador para que sea tu 'guardaespaldas' un turno.", r: { happy: 2 }, i: "🛡️", c: "bg-blue-100" },
    { t: "Dibuja un gato con los ojos cerrados en 20 segundos. Si parece un gato.", r: { happy: 2 }, i: "🐱", c: "bg-blue-100" },
    { t: "Inventa un nombre de superhéroe para el jugador de tu derecha.", r: { happy: 1 }, i: "🦸", c: "bg-blue-100" },
    { t: "Haz 10 flexiones de pecho (o sentadillas).", r: { health: 3 }, i: "💪", c: "bg-blue-100" },
    { t: "Habla con acento extranjero (tú eliges) durante 2 turnos.", r: { happy: 2 }, i: "🗣️", c: "bg-blue-100" },
    { t: "Pide prestado $1,000 a un jugador (si acepta, se lo devuelves después).", r: { money: 1000 }, i: "🤝", c: "bg-blue-100" },
    { t: "Cierra los ojos y que alguien te ponga un objeto en la mano. Adivina qué es.", r: { happy: 2 }, i: "🧤", c: "bg-blue-100" },
    { t: "Grita '¡Soy el rey del éxito!' con pasión.", r: { happy: 1 }, i: "👑", c: "bg-blue-100" },
    { t: "Haz una rima rápida de 4 versos sobre este juego.", r: { happy: 2 }, i: "📝", c: "bg-blue-100" },
    { t: "Actúa en cámara lenta durante 15 segundos.", r: { happy: 2 }, i: "🐢", c: "bg-blue-100" },
    { t: "Nombra 5 películas de superhéroes en 10 segundos.", r: { money: 1000 }, i: "🎬", c: "bg-blue-100" },
    { t: "Haz equilibrio sobre un pie durante 20 segundos.", r: { health: 2 }, i: "🧘", c: "bg-blue-100" },
    { t: "Dile un cumplido sincero a cada jugador.", r: { happy: 3 }, i: "❤️", c: "bg-blue-100" },
    { t: "Simula que eres un robot pidiendo un café.", r: { happy: 2 }, i: "🤖", c: "bg-blue-100" },
    { t: "Haz mímica de una película clásica. Si alguien la adivina.", r: { happy: 2 }, i: "📽️", c: "bg-blue-100" },
    { t: "Regala $500 a cada jugador. Si lo haces, ganas felicidad.", r: { happy: 3 }, i: "🎁", c: "bg-blue-100" },
    { t: "Haz 5 saltos de tijera gritando tu nombre.", r: { health: 2, happy: 1 }, i: "🤸", c: "bg-blue-100" },
    { t: "Cuenta hasta 10 en otro idioma (que no sea español/inglés).", r: { money: 1000 }, i: "🌍", c: "bg-blue-100" },
    { t: "Imita el sonido de 3 animales diferentes.", r: { happy: 1 }, i: "🐷", c: "bg-blue-100" },
    { t: "Haz una propuesta de 'negocio' absurda a otro jugador.", r: { money: 1000, happy: 1 }, i: "💡", c: "bg-blue-100" },
    { t: "¡SORPRESA! Tira el dado. Si sale 6, ganas $3k. Si sale 1, pierdes $2k.", r: { money: 0 }, i: "🎲", c: "bg-blue-100" }
];

export const mazoExpertis: Card[] = [
    { t: "Haz una pausa de 10 segundos y respira profundo.", r: { health: 2 }, i: "🌬️", c: "bg-green-100" },
    { t: "Recuerda y cuenta una lección difícil de tu vida.", r: { money: 1000, health: 1, happy: 1 }, i: "📚", c: "bg-green-100" },
    { t: "Comparte con el grupo algo que te hizo fuerte.", r: { money: 1000, happy: 2 }, i: "💪", c: "bg-green-100" },
    { t: "Reflexiona en silencio 10 segundos sobre lo que más valoras.", r: { health: 2, happy: 1 }, i: "💭", c: "bg-green-100" },
    { t: "Párate frente a un espejo imaginario y di: 'Estoy avanzado'.", r: { health: 2, happy: 1 }, i: "🪞", c: "bg-green-100" },
    { t: "Platica a los demás de un libro que te cambió.", r: { money: 2000, happy: 2 }, i: "📖", c: "bg-green-100" },
    { t: "Simula que caminas por un bosque y cuenta qué sientes.", r: { health: 3 }, i: "🌲", c: "bg-green-100" },
    { t: "Da un consejo a un jugador menor que tú.", r: { happy: 1 }, i: "🤝", c: "bg-green-100" },
    { t: "Comenta de un error que cometiste y lo que aprendiste.", r: { health: 2 }, i: "📉", c: "bg-green-100" },
    { t: "Comenta un momento en que decidiste cambiar.", r: { money: 1000, health: 1, happy: 1 }, i: "🔄", c: "bg-green-100" },
    { t: "Cuéntale al grupo qué cosa maravillosa harás la siguiente semana.", r: { health: 2 }, i: "📅", c: "bg-green-100" },
    { t: "Finge que recibes un premio por ser el mejor escritor.", r: { money: 1000, happy: 1 }, i: "🏆", c: "bg-green-100" },
    { t: "Simula que estás grabando un podcast de motivación (30 seg).", r: { money: 2000, happy: 1 }, i: "🎙️", c: "bg-green-100" },
    { t: "Pregúntale a alguien: ¿Qué lo hace feliz?", r: { happy: 2 }, i: "❓", c: "bg-green-100" },
    { t: "Tienes que decirle a todos 3 metas para tu siguiente mes.", r: { health: 1, happy: 1 }, i: "🎯", c: "bg-green-100" },
    { t: "Canta un pedazo de una canción que te inspira.", r: { health: 1, happy: 1, money: 1000 }, i: "🎤", c: "bg-green-100" },
    { t: "Te toca reflexionar, quédate en silencio hasta que vuelvas a tirar.", r: { health: 2, happy: 2 }, i: "🤫", c: "bg-green-100" },
    { t: "Si puedes decir qué número de día es hoy sin ver tu celular.", r: { health: 2 }, i: "📆", c: "bg-green-100" },
    { t: "Toma agua y haz un brindis por tu progreso.", r: { health: 1, happy: 1 }, i: "🥛", c: "bg-green-100" },
    { t: "Finge y posa que te toman una foto de tu versión futura exitosa.", r: { happy: 2 }, i: "📸", c: "bg-green-100" },
    { t: "Analiza tu estrategia actual en voz alta. El grupo decide si es buena.", r: { money: 2000, happy: 1 }, i: "📊", c: "bg-green-100" },
    { t: "Lanzamiento de producto fallido. Aprendes la lección.", r: { money: -2000, happy: 3 }, i: "📉", c: "bg-green-100" },
    { t: "Networking efectivo: conoce 'virtualmente' a un nuevo socio.", r: { money: 3000, happy: 1 }, i: "🤝", c: "bg-green-100" },
    { t: "Tu marca personal se vuelve viral por un día.", r: { happy: 5, money: 1000 }, i: "✨", c: "bg-green-100" },
    { t: "Mentoría de un experto: te da un consejo clave.", r: { money: 2000, health: 1 }, i: "👨‍🏫", c: "bg-green-100" },
    { t: "Optimización de procesos: ahorras tiempo y recursos.", r: { money: 2000, health: 1 }, i: "⚙️", c: "bg-green-100" },
    { t: "Crisis de reputación: manejas el problema con elegancia.", r: { happy: 2, health: -1 }, i: "📣", c: "bg-green-100" },
    { t: "Inviertes en el crecimiento de tu equipo.", r: { money: -3000, happy: 4 }, i: "👥", c: "bg-green-100" },
    { t: "Auditoría sorpresa: todo está en orden.", r: { money: 2000 }, i: "📋", c: "bg-green-100" },
    { t: "Descubres un nuevo nicho de mercado.", r: { money: 3000 }, i: "🔍", c: "bg-green-100" },
    { t: "Huelga de inspiración. Tómate un respiro.", r: { health: 3, happy: -1 }, i: "🧘", c: "bg-green-100" },
    { t: "Un cliente antiguo vuelve con un proyecto grande.", r: { money: 4000 }, i: "🔄", c: "bg-green-100" },
    { t: "Tu oficina se inunda. Pérdidas materiales pero equipo unido.", r: { money: -4000, happy: 3 }, i: "🌊", c: "bg-green-100" },
    { t: "Ganas una licitación pública.", r: { money: 5000 }, i: "📝", c: "bg-green-100" },
    { t: "Día de retiro espiritual para el SEO.", r: { health: 4, happy: 2 }, i: "⛪", c: "bg-green-100" },
    { t: "Tu competencia te copia. Te sientes halagado pero alerta.", r: { happy: 2, money: -1000 }, i: "👯", c: "bg-green-100" },
    { t: "Automatizas una tarea tediosa.", r: { happy: 3, health: 2 }, i: "🤖", c: "bg-green-100" },
    { t: "Das una entrevista en un medio importante.", r: { money: 2000, happy: 4 }, i: "🎤", c: "bg-green-100" },
    { t: "Colaboración con una celebridad (finge que hablas con ella).", r: { happy: 4, money: 3000 }, i: "🌟", c: "bg-green-100" },
    { t: "Encuentras un inversor ángel.", r: { money: 6000 }, i: "👼", c: "bg-green-100" },
    { t: "Día de formación para ti: aprendes sobre IA.", r: { money: 2000, happy: 2 }, i: "💻", c: "bg-green-100" },
    { t: "Hackeo de base de datos. Gastas en seguridad.", r: { money: -5000, health: -2 }, i: "🛡️", c: "bg-green-100" },
    { t: "Premio al 'Emprendedor Revelación'.", r: { happy: 6, money: 2000 }, i: "🏆", c: "bg-green-100" },
    { t: "Tu familia te apoya en un momento de duda.", r: { happy: 5, health: 3 }, i: "❤️", c: "bg-green-100" },
    { t: "Cambio de sede a un lugar mejor.", r: { money: -4000, happy: 5 }, i: "🏢", c: "bg-green-100" },
    { t: "Un error de cálculo te favorece inesperadamente.", r: { money: 3000, happy: 1 }, i: "💹", c: "bg-green-100" },
    { t: "Haces un voluntariado corporativo.", r: { happy: 6, health: 2 }, i: "🤝", c: "bg-green-100" },
    { t: "Te vuelves mentor de un joven talento.", r: { happy: 4 }, i: "🌱", c: "bg-green-100" },
    { t: "Día de desconexión absoluta. Vuelves con todo.", r: { health: 5, happy: 3 }, i: "🔋", c: "bg-green-100" },
    { t: "¡ÉXITO TOTAL! Tu empresa sale a bolsa.", r: { money: 10000, happy: 5 }, i: "🏛️", c: "bg-green-100" }
];

export const mazoRutas: { [key: string]: Card[] } = {
    IMPACTO: [
        { t: "Pinta ahora mismo algo que te representa.", r: { happy: 4 }, i: "🎨", requiresJudgment: true },
        { t: "Canta un pedazo de tu canción favorita.", r: { happy: 4, health: 2 }, i: "🎤", requiresJudgment: true },
        { t: "Tomaste ayer una foto creativa. Descríbela.", r: { happy: 3 }, i: "📸", requiresJudgment: true },
        { t: "Actúa como influencer motivacional.", r: { happy: 5, money: 3000 }, i: "📱", requiresJudgment: true },
        { t: "Escribiste ya un microcuento brillante. Cuéntalo.", r: { happy: 3 }, i: "✍️", requiresJudgment: true },
        { t: "Te plagian una idea.", r: { happy: -3, health: -2 }, i: "🚫" },
        { t: "Haz un baile divertido de 10 segundos.", r: { happy: 4, health: 3 }, i: "💃", requiresJudgment: true },
        { t: "Publicaste un video inspirador. Descríbelo.", r: { happy: 4 }, i: "📹", requiresJudgment: true },
        { t: "Diseñaste un logo para un amigo.", r: { happy: 2, money: 2000 }, i: "✏️" },
        { t: "Premio a la creatividad del mes.", r: { happy: 5 }, i: "🏆" },
        { t: "Exposición en una galería local.", r: { happy: 6, money: 2000 }, i: "🖼️" },
        { t: "Escribes una canción que se vuelve viral.", r: { happy: 5, money: 2000 }, i: "🎼" },
        { t: "Te quedas sin tinta justo antes de terminar.", r: { happy: -2, money: -1000 }, i: "🖍️" },
        { t: "Colaboras con otro artista. Regalale 2 de felicidad.", r: { happy: 4 }, i: "🤝" },
        { t: "Ganas un concurso de fotografía.", r: { happy: 5, money: 3000 }, i: "📷" },
        { t: "Ilustras un libro infantil.", r: { happy: 4, money: 2000 }, i: "🎨" },
        { t: "Crítica destructiva de un experto.", r: { happy: -3, health: -1 }, i: "🗞️" },
        { t: "Haces un mural en la ciudad.", r: { happy: 6, health: 4 }, i: "🧱" },
        { t: "Das un taller de arte a niños.", r: { happy: 5 }, i: "🧒" },
        { t: "Diseñas la portada de una revista.", r: { happy: 4, money: 3000 }, i: "📖" },
        { t: "Participas en un slam de poesía.", r: { happy: 5, health: 1 }, i: "🎤" },
        { t: "Tu arte decora un café famoso.", r: { happy: 4, money: 1000 }, i: "☕" },
        { t: "Haces un diseño para una ONG gratis.", r: { happy: 7 }, i: "🕊️" },
        { t: "Recibes una beca de creación artística.", r: { money: 2000, happy: 2 }, i: "📜" },
        { t: "Bloqueo creativo profundo.", r: { health: 2, happy: -2 }, i: "🚫" },
        { t: "Vendes tu primera obra en NFT.", r: { money: 4000 }, i: "💻" },
        { t: "Haces el diseño de vestuario para una obra.", r: { happy: 4, money: 2000 }, i: "🎭" },
        { t: "Te invitan a un podcast de arte.", r: { happy: 3, money: 1000 }, i: "🎙️" },
        { t: "Creas una identidad visual para una startup.", r: { money: 3000 }, i: "✨" },
        { t: "OBRA MAESTRA: Todo el mundo habla de tu genio.", r: { happy: 10, money: 5000 }, i: "💎" }
    ],
    BIENESTAR: [
        { t: "Duermes 8 horas de calidad.", r: { health: 4, happy: 2 }, i: "😴" },
        { t: "Sesión de terapia efectiva.", r: { health: 4 }, i: "🛋️" },
        { t: "Entrenas con un amigo. Pídele que hagan juntos 3 sentadillas.", r: { health: 3 }, i: "🏋️", requiresJudgment: true },
        { t: "Comes sano 3 días seguidos.", r: { health: 4 }, i: "🥗" },
        { t: "Te felicitan por tu cambio positivo.", r: { happy: 3 }, i: "👏" },
        { t: "Te lesionas entrenando.", r: { health: -5 }, i: "🤕" },
        { t: "Día de spa y relajación profunda.", r: { health: 4, happy: 3 }, i: "🧖" },
        { t: "Meditas 5 minutos en silencio.", r: { health: 4 }, i: "🧘" },
        { t: "Apagaste el celular 30 min. todos los días.", r: { health: 3, happy: 2 }, i: "📵" },
        { t: "Decides tomar un smoothie verde poderoso.", r: { health: 2 }, i: "🥤" },
        { t: "Terminas un maratón de 5km.", r: { health: 6, happy: 4 }, i: "跑步" },
        { t: "Empiezas a practicar yoga matutino.", r: { health: 5, happy: 2 }, i: "🧘" },
        { t: "Comes demasiada comida chatarra.", r: { health: -4, happy: 1 }, i: "🍔" },
        { t: "Haces un chequeo médico completo.", r: { health: 5 }, i: "🩺" },
        { t: "Adoptas una mascota que te llena de alegría.", r: { happy: 4, health: 1 }, i: "🐶" },
        { t: "Aprendes a cocinar 3 recetas nutritivas.", r: { health: 4, happy: 2 }, i: "🍲" },
        { t: "Te apuntas a clases de baile.", r: { health: 4, happy: 4 }, i: "💃" },
        { t: "Día de campo con familia sin móviles.", r: { happy: 6, health: 3 }, i: "🧺" },
        { t: "Suplementos vitamínicos que funcionan.", r: { health: 3 }, i: "💊" },
        { t: "Te regalas una tarde de lectura al sol.", r: { happy: 4, health: 2 }, i: "☀️" },
        { t: "Problemas de espalda por mala postura.", r: { health: -3 }, i: "🪑" },
        { t: "Haces una desintoxicación digital.", r: { health: 4, happy: 4 }, i: "📵" },
        { t: "Bebes 2 litros de agua al día.", r: { health: 5 }, i: "💧" },
        { t: "Te dan un masaje profesional.", r: { health: 6, happy: 4 }, i: "💆" },
        { t: "Participas en un retiro de meditación.", r: { health: 5, happy: 5 }, i: "📿" },
        { t: "Resfriado común. Reposo.", r: { health: -2, happy: -1 }, i: "🤧" },
        { t: "Aprendes técnicas de respiración consciente.", r: { health: 4 }, i: "🌬️" },
        { t: "Visitas a un viejo amigo y ríen horas.", r: { happy: 7 }, i: "👬" },
        { t: "Plantas un huerto en casa.", r: { happy: 4, health: 2 }, i: "🌱" },
        { t: "SALUD DE HIERRO: Te sientes rejuvenecido.", r: { health: 10, happy: 5 }, i: "🛡️" }
    ],
    CARRERA: [
        { t: "Consigues tu primer empleo.", r: { money: 4000 }, i: "👔" },
        { t: "Tu jefe te reconoce públicamente.", r: { happy: 4 }, i: "🤝" },
        { t: "Llegas tarde a una reunión clave.", r: { money: -2000, happy: -2 }, i: "⏰" },
        { t: "Te ascienden a coordinador.", r: { money: 6000 }, i: "📈" },
        { t: "Recorte de personal: te despiden.", r: { money: -6000, happy: -3 }, i: "📦" },
        { t: "Cierras un gran contrato.", r: { money: 8000 }, i: "✍️" },
        { t: "Horas extra sin pago.", r: { happy: -3 }, i: "😫" },
        { t: "Eres el empleado del mes.", r: { happy: 4, health: 2 }, i: "🏅" },
        { t: "Error con un cliente importante.", r: { money: -2000, happy: -2 }, i: "❌" },
        { t: "Tu equipo logra un objetivo clave.", r: { money: 4000, happy: 3 }, i: "🎯" },
        { t: "Lideras un proyecto internacional.", r: { money: 7000, happy: 3 }, i: "🌍" },
        { t: "Tu mentor en la empresa te felicita.", r: { happy: 5 }, i: "👨‍🏫" },
        { t: "Te quitan el crédito de un trabajo.", r: { happy: -5, health: -2 }, i: "🙅" },
        { t: "Curso de capacitación pagado por la empresa.", r: { money: 2000, happy: 2 }, i: "🎓" },
        { t: "Consigues un aumento de sueldo.", r: { money: 5000 }, i: "💰" },
        { t: "Estrés por entregas finales.", r: { health: -4, happy: -2 }, i: "🤯" },
        { t: "Fiesta de fin de año de la empresa.", r: { happy: 4, money: 1000 }, i: "🎉" },
        { t: "Te ofrecen una posición en otra ciudad.", r: { money: 6000, happy: 2 }, i: "✈️" },
        { t: "Conflictos con un compañero de equipo.", r: { happy: -3, health: -1 }, i: "😠" },
        { t: "Mejoran las condiciones de tu oficina.", r: { health: 3, happy: 3 }, i: "🏢" },
        { t: "Haces una presentación impecable al CEO.", r: { happy: 6, money: 2000 }, i: "📊" },
        { t: "Recibes un bono por productividad.", r: { money: 4000 }, i: "💵" },
        { t: "Burnout. Tienes que parar un momento.", r: { health: -8, happy: -4 }, i: "🕯️" },
        { t: "Te nombran representante de los empleados.", r: { happy: 4 }, i: "🗣️" },
        { t: "Trabajo remoto: ahorras en transporte.", r: { money: 2000, health: 3 }, i: "🏠" },
        { t: "Un headhunter te llama con una oferta.", r: { happy: 4 }, i: "📞" },
        { t: "Lanzamiento exitoso de un producto.", r: { money: 5000, happy: 4 }, i: "🚀" },
        { t: "Te toca organizar el evento del año.", r: { health: -3, happy: 5 }, i: "📅" },
        { t: "Logras un equilibrio trabajo-vida.", r: { health: 6, happy: 6 }, i: "⚖️" },
        { t: "PRESIDENCIA: Llegas a la cima corporativa.", r: { money: 10000, happy: 6 }, i: "🏢" }
    ],
    ESPIRITU: [
        { t: "Prototipas tu primer producto.", r: { money: 4000 }, i: "🛠️" },
        { t: "Tu inventario llega tarde.", r: { money: -2000, happy: -2 }, i: "🚚" },
        { t: "Abres tu primera tienda/pop-up.", r: { money: 6000 }, i: "🏪" },
        { t: "Haces tu primer reel de anuncio.", r: { money: 4000 }, i: "📱" },
        { t: "Te critican en redes.", r: { happy: -3, health: -1 }, i: "👎" },
        { t: "Cierra una venta gigante.", r: { money: 8000 }, i: "💲" },
        { t: "Bloqueo financiero: te quedas sin liquidez.", r: { money: -3000 }, i: "💸" },
        { t: "Delegas como pro tus actividades.", r: { money: 4000, health: 3 }, i: "👥" },
        { t: "Cliente satisfecho te recomienda.", r: { happy: 4 }, i: "🗣️" },
        { t: "Lanzas un nuevo servicio.", r: { money: 4000, happy: 2 }, i: "🆕" },
        { t: "Consigues inversión de un familiar.", r: { money: 5000 }, i: "👨‍👩‍👧" },
        { t: "Tu página web se cae en el lanzamiento.", r: { money: -3000, happy: -4 }, i: "💻" },
        { t: "Primer pedido masivo de un cliente.", r: { money: 5000 }, i: "📦" },
        { t: "Contratas a tu primer empleado.", r: { money: -2000, happy: 5 }, i: "👥" },
        { t: "Pivoteas tu modelo de negocio con éxito.", r: { money: 4000, happy: 4 }, i: "🔄" },
        { t: "Demanda por propiedad intelectual.", r: { money: -8000, health: -5 }, i: "⚖️" },
        { t: "Ganas un concurso de startups.", r: { money: 6000, happy: 3 }, i: "🏆" },
        { t: "Te invitan a ser speaker en un evento.", r: { money: 3000, happy: 5 }, i: "🎙️" },
        { t: "Un socio te traiciona. Pierdes capital.", r: { money: -5000, happy: -6 }, i: "💔" },
        { t: "Campaña de crowdfunding exitosa.", r: { money: 5000 }, i: "💰" },
        { t: "Apareces en el top de la App Store.", r: { money: 4000, happy: 4 }, i: "📱" },
        { t: "Problemas de logística en aduanas.", r: { money: -4000, health: -3 }, i: "⚓" },
        { t: "Tu producto sale en un programa de TV.", r: { money: 8000, happy: 4 }, i: "📺" },
        { t: "Expandas tu negocio a otro país.", r: { money: 6000, happy: 2 }, i: "🌏" },
        { t: "Hackaton interna: sale una idea millonaria.", r: { money: 5000, happy: 6 }, i: "💡" },
        { t: "Falla eléctrica quema tus servidores.", r: { money: -6000 }, i: "🔥" },
        { t: "Logras rentabilidad (Break Even).", r: { happy: 10, money: 5000 }, i: "📈" },
        { t: "Te conviertes en referente industrial.", r: { happy: 7, money: 3000 }, i: "👑" },
        { t: "Vendes franquicias de tu negocio.", r: { money: 10000 }, i: "🏠" },
        { t: "EXIT: Vendes tu empresa por millones.", r: { money: 15000, happy: 10 }, i: "🚀" }
    ],
    FORMACION: [
        { t: "Te inscribes a un curso intensivo.", r: { happy: 4, money: 2000 }, i: "📚" },
        { t: "Celebra que terminaste tu diplomado con honores.", r: { happy: 6 }, i: "🎓" },
        { t: "Dinos un libro que te cambió la perspectiva.", r: { happy: 2 }, i: "📖", requiresJudgment: true },
        { t: "Aprendes un idioma nuevo.", r: { happy: 4 }, i: "🗣️" },
        { t: "Te presentas en público por primera vez.", r: { happy: 4 }, i: "🎤", requiresJudgment: true },
        { t: "Obtienes una beca educativa.", r: { money: 4000 }, i: "📝" },
        { t: "Das una clase virtual.", r: { happy: 6 }, i: "💻", requiresJudgment: true },
        { t: "Te gradúas como coach certificado.", r: { happy: 4, money: 4000 }, i: "🏅" },
        { t: "Cuenta qué hace la nueva app que programaste.", r: { money: 4000 }, i: "📱", requiresJudgment: true },
        { t: "Tomaste un curso de finanzas.", r: { money: 2000, happy: 2 }, i: "💹" },
        { t: "Terminas un máster en línea.", r: { happy: 5, money: 2000 }, i: "💻" },
        { t: "Aprendes a programar en Python.", r: { money: 4000, happy: 3 }, i: "🐍" },
        { t: "Suspendes un examen importante.", r: { happy: -4, money: -1000 }, i: "📝" },
        { t: "Te invitan a dar una conferencia escolar.", r: { happy: 8 }, i: "🏫" },
        { t: "Escribes un artículo académico citado.", r: { happy: 6, money: 1000 }, i: "📄" },
        { t: "Pierdes tu título por error administrativo.", r: { health: -2, happy: 2 }, i: "📜" },
        { t: "Consigues una certificación internacional.", r: { money: 5000, happy: 4 }, i: "🌏" },
        { t: "Haces un curso de cocina gourmet.", r: { happy: 6, health: 3 }, i: "👨‍🍳" },
        { t: "Viajas para un congreso de 3 días.", r: { happy: 5, money: -2000 }, i: "✈️" },
        { t: "Aprendes a tocar un instrumento.", r: { happy: 7, health: 1 }, i: "🎸" },
        { t: "Lees 50 libros en un año.", r: { happy: 5, health: 1 }, i: "📚" },
        { t: "Haces un curso de oratoria.", r: { happy: 5, money: 2000 }, i: "🗣️" },
        { t: "Aprendes sobre finanzas personales.", r: { money: 6000 }, i: "💹" },
        { t: "Aprendes a meditar con un maestro.", r: { health: 8, happy: 5 }, i: "🧘" },
        { t: "Te conviertes en políglota.", r: { happy: 6, money: 2000 }, i: "🗣️" },
        { t: "No entiendes nada en una clase avanzada.", r: { happy: -3 }, i: "😵" },
        { t: "Participas en un campamento de ciencia.", r: { happy: 5, money: 1000 }, i: "🧪" },
        { t: "Haces un curso de primeros auxilios.", r: { health: 10 }, i: "🚑" },
        { t: "Premio al 'Estudiante de la Década'.", r: { happy: 10, money: 4000 }, i: "🎓" },
        { t: "SABIDURÍA INFINITA: Tu mayor activo.", r: { happy: 15, money: 2000 }, i: "🧠" }
    ],
    INVERSION: [
        { t: "Cripto al alza: tomas ganancia.", r: { money: 6000 }, i: "🚀" },
        { t: "Cripto a la baja: caes con mercado.", r: { money: -4000 }, i: "📉" },
        { t: "Recibes dividendos extraordinarios.", r: { money: 6000 }, i: "💵" },
        { t: "La burbuja explota: pérdida total.", r: { money: -5000 }, i: "💥" },
        { t: "Compras un piso para renta.", r: { passive: 2000 }, i: "🏢" },
        { t: "Un podcast financiero te ilumina.", r: { happy: 3, health: 2 }, i: "🎧" },
        { t: "Interés compuesto a tu favor.", r: { money: 4000 }, i: "🔄" },
        { t: "Inviertes en algo ilegal sin saber.", r: { money: -4000, happy: -3 }, i: "🚔" },
        { t: "Vendes antes de la crisis.", r: { money: 8000 }, i: "🛑" },
        { t: "Compras acciones y suben fuerte.", r: { money: 6000 }, i: "📈" },
        { t: "Inviertes en una startup y sale bien.", r: { money: 12000 }, i: "🚀" },
        { t: "Tu asesor financiero desaparece.", r: { money: -15000, health: -5 }, i: "🏃" },
        { t: "Compras un local comercial.", r: { passive: 3000 }, i: "🏪" },
        { t: "Inviertes en oro y el precio sube.", r: { money: 8000 }, i: "🪙" },
        { t: "Crash bursátil global. Prepárate.", r: { money: -10000 }, i: "📉" },
        { t: "Recibes una herencia inesperada.", r: { money: 15000 }, i: "🎁" },
        { t: "Tu cartera de criptomonedas es hackeada.", r: { money: -10000 }, i: "🔓" },
        { t: "Compras acciones de una tecnológica.", r: { money: 15000 }, i: "💻" },
        { t: "El mercado inmobiliario se dispara.", r: { money: 20000 }, i: "🏗️" },
        { t: "Intereses bancarios a tu favor.", r: { money: 3000 }, i: "🏦" },
        { t: "Inviertes en arte y se revaloriza.", r: { money: 10000, happy: 5 }, i: "🖼️" },
        { t: "Cae tu rendimiento por inflación.", r: { money: -4000 }, i: "💸" },
        { t: "Consigues un socio capitalista fuerte.", r: { money: 10000 }, i: "🤝" },
        { t: "Compras bonos del estado seguros.", r: { passive: 2000 }, i: "📜" },
        { t: "Especulación fallida en mercado externo.", r: { money: -12000 }, i: "🌍" },
        { t: "Tu negocio genera excedente.", r: { money: 10000 }, i: "🔄" },
        { t: "Descubres una gema oculta en bolsa.", r: { money: 15000 }, i: "💎" },
        { t: "Pagas una multa a Hacienda.", r: { money: -5000, happy: -3 }, i: "⚖️" },
        { t: "Tu estrategia de dividendos da frutos.", r: { money: 8000 }, i: "💵" },
        { t: "FORTUNA: Te conviertes en gran inversor.", r: { money: 15000 }, i: "💰" }
    ],
    LIBERTAD: [
        { t: "Logras la independencia económica.", r: { money: 7000 }, i: "🔓" },
        { t: "Vives de tus rentas.", r: { money: 3000, health: 1 }, i: "🏖️" },
        { t: "Tomas vacaciones sin preocuparte.", r: { happy: 5, health: 2 }, i: "🌴" },
        { t: "Cubres gastos sin trabajar.", r: { passive: 1000, happy: 2 }, i: "💳" },
        { t: "Automatizas tus ingresos.", r: { passive: 1000 }, i: "⚙️" },
        { t: "Inviertes en propiedades de lujo.", r: { money: 6000 }, i: "🏰" },
        { t: "Pagas todas tus deudas.", r: { happy: 5, health: 3 }, i: "✂️" },
        { t: "Compras tu casa de ensueño.", r: { happy: 5 }, i: "🏡" },
        { t: "Trabajas solo por gusto.", r: { happy: 4, health: 2 }, i: "❤️" },
        { t: "Lograste tu semana ideal.", r: { happy: 4 }, i: "📅" },
        { t: "Vendes tu casa y te mudas a la playa.", r: { happy: 8, health: 5 }, i: "🏖️" },
        { t: "Tus rentas cubren el 200% de gastos.", r: { money: 5000, happy: 3 }, i: "💳" },
        { t: "Haces un viaje alrededor del mundo.", r: { happy: 10, health: 4, money: -10000 }, i: "🚢" },
        { t: "Donas una gran suma a una causa.", r: { happy: 12, money: -10000 }, i: "🕊️" },
        { t: "Tus pasivos crecen solos.", r: { passive: 2000 }, i: "⚙️" },
        { t: "Pierdes la noción del tiempo de relax.", r: { health: 8, happy: 5 }, i: "🕰️" },
        { t: "Comprás un yate (o un barco de papel).", r: { happy: 5, money: -8000 }, i: "🚤" },
        { t: "Vives de tu pasión sin mirar el banco.", r: { happy: 8, health: 5 }, i: "🎨" },
        { t: "Hijos heredan tu mentalidad ganadora.", r: { happy: 10 }, i: "👪" },
        { t: "Haces una fiesta épica para todos.", r: { happy: 8, money: -3000 }, i: "🎉" },
        { t: "Libertad de agenda: sin despertador.", r: { health: 12, happy: 8 }, i: "⏰" },
        { t: "Invitas a tu familia a vacaciones de lujo.", r: { happy: 10, money: -5000 }, i: "🏰" },
        { t: "Tu tranquilidad mental no tiene precio.", r: { health: 10, happy: 10 }, i: "🧘" },
        { t: "Escribes tus memorias para inspirar.", r: { happy: 10, money: 5000 }, i: "✍️" },
        { t: "Te retiras oficialmente. Ya ganaste.", r: { happy: 15, health: 10 }, i: "🏁" },
        { t: "Vuelves a empezar un proyecto por gusto.", r: { happy: 10, money: 4000 }, i: "🆕" },
        { t: "Tu legado perdura en una fundación.", r: { happy: 20, money: -10000 }, i: "🏛️" },
        { t: "Te mudas a un piso en el centro.", r: { money: -10000, happy: 10 }, i: "🏙️" },
        { t: "Eres totalmente dueño de tu tiempo.", r: { happy: 15, health: 12 }, i: "⏳" },
        { t: "ILUMINACIÓN: Salud y felicidad al máximo.", r: { health: 25, happy: 25 }, i: "✨" }
    ],
    LIDERAZGO: [
        { t: "Tomas el rol de líder.", r: { happy: 4, health: 3 }, i: "👑" },
        { t: "Da una charla que inspira.", r: { happy: 5 }, i: "🗣️", requiresJudgment: true },
        { t: "Dale un consejo a otro jugador.", r: { happy: 3 }, i: "👯", requiresJudgment: true },
        { t: "Te gradúas como mentor.", r: { happy: 4, money: 4000 }, i: "🎓" },
        { t: "Pídele a algún jugador una crítica tuya.", r: { happy: -2, money: 2000 }, i: "📉", requiresJudgment: true },
        { t: "Reconoce públicamente a tus amigos.", r: { happy: 4 }, i: "🏆", requiresJudgment: true },
        { t: "Delegas con maestría.", r: { money: 4000, health: 2 }, i: "🧩" },
        { t: "Diseñas un plan estratégico ganador.", r: { money: 6000 }, i: "🗺️" },
        { t: "Enseñas a un niño algo valioso.", r: { happy: 4 }, i: "👶", requiresJudgment: true },
        { t: "Gestionaste una crisis con calma.", r: { happy: 3, health: 2 }, i: "🔥" },
        { t: "Tu equipo te sorprende con un regalo.", r: { happy: 10 }, i: "🎁" },
        { t: "Resuelves una huelga con diálogo.", r: { happy: 8, health: 4 }, i: "🤝" },
        { t: "Te invitan a ser mentor de un CEO.", r: { happy: 6, money: 3000 }, i: "👨‍🏫" },
        { t: "Tu discurso de graduación motiva.", r: { happy: 15, money: 5000 }, i: "🎓" },
        { t: "Fallo en liderazgo: renuncia masiva.", r: { happy: -10, money: -5000 }, i: "📉" },
        { t: "Jornadas de 4 días: sube productividad.", r: { happy: 12, health: 10 }, i: "📆" },
        { t: "Escribes un Best Seller sobre liderazgo.", r: { money: 10000, happy: 10 }, i: "📚" },
        { t: "Te eligen 'Líder del Año'.", r: { happy: 10, money: 5000 }, i: "🏅" },
        { t: "Gestionas crisis de salud en empresa.", r: { health: 8, happy: 3 }, i: "🚑" },
        { t: "Crees en alguien marginado y triunfa.", r: { happy: 12 }, i: "✨" },
        { t: "Haces un retiro de liderazgo.", r: { health: 10, happy: 10, money: -4000 }, i: "⛰️" },
        { t: "Delegas dirección y tomas sabático.", r: { happy: 15, health: 15 }, i: "🛋️" },
        { t: "Tu filosofía se estudia en universidades.", r: { happy: 10, money: 8000 }, i: "🏛️" },
        { t: "Creas una cultura de transparencia.", r: { happy: 8, health: 5 }, i: "💎" },
        { t: "Te enfrentas a un dilema ético positivo.", r: { happy: 20 }, i: "⚖️" },
        { t: "Tu carisma atrae al mejor talento.", r: { money: 8000, happy: 3 }, i: "🧲" },
        { t: "Formas a tu sucesor con éxito.", r: { happy: 10, money: 10000 }, i: "🔄" },
        { t: "Recibes medalla de honor al mérito.", r: { happy: 25 }, i: "🎖️" },
        { t: "Tu empresa es el mejor lugar para trabajar.", r: { happy: 15, money: 7000 }, i: "🌎" },
        { t: "LÍDER DE LÍDERES: Cambias el mundo.", r: { happy: 30, health: 15, money: 15000 }, i: "👑" }
    ]
};
export const routeCosts: { [key: string]: number } = { IMPACTO: 1000, BIENESTAR: 1000, CARRERA: 3000, ESPIRITU: 3000, FORMACION: 3000, INVERSION: 4000, LIBERTAD: 2000, LIDERAZGO: 2000 };

export const mainBoard: Tile[] = [
    { n: "Inicio", t: "ESQUINA", d: "Cobra Ingreso Pasivo", i: "🏠" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "Día de Spa", t: "RELAX", d: "No pasa nada. Relájate.", i: "🧖" },
    { n: "Reto", t: "CARTA", c: "RETO", d: "Toma una carta de 'Oportunidad'", i: "⚡" },
    { n: "Formación", t: "ENTRADA", r: "FORMACION", d: "Entra a la ruta de Formación", i: "🎓" },
    { n: "Restaurante", t: "DADO_EVENTO", d: "Te toca pagar la cuenta. Tira dado: Paga $1,000 x punto.", i: "🍽️" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "Carrera Corp", t: "ENTRADA", r: "CARRERA", d: "Entra a la ruta de Carrera Corporativa", i: "💼" },
    { n: "Reto", t: "CARTA", c: "RETO", d: "Toma una carta de 'Oportunidad'", i: "⚡" },
    { n: "Causa Social", t: "DADO_EVENTO", d: "Tira dado: Ganas $1,000 x punto y donas.", i: "🤝" },
    { n: "SUERTE", t: "ESQUINA", d: "Te llevas el Pozo acumulado.", i: "🍀" },
    { n: "Todos Donan", t: "MULTA", a: 1000, d: "Todos donan $1,000 al Pozo.", global: true, i: "🤲" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "Contaminación", t: "DADO_EVENTO", d: "Riesgo de enfermedad. Tira dado: Pierdes 1 Salud x punto.", i: "😷" },
    { n: "Espíritu Emprendedor", t: "ENTRADA", r: "ESPIRITU", d: "Entra a la ruta de Espíritu Emprendedor", i: "💡" },
    { n: "Demanda", t: "DADO_EVENTO", d: "Paga $1,000 x punto del dado", i: "⚖️" },
    { n: "Reto", t: "CARTA", c: "RETO", d: "Toma una carta de 'Oportunidad'", i: "⚡" },
    { n: "Inversión Inteligente", t: "ENTRADA", r: "INVERSION", d: "Entra a la ruta de Inversión", i: "📈" },
    { n: "Día de Suerte", t: "BONUS", a: 0, d: "El jugador de tu derecha te regala 1 de felicidad y 1 de salud.", i: "😊" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "VACACIONES", t: "ESQUINA", d: "Tira Dado. Pagas $1,000 por punto y ganas 1 Felicidad por punto.", i: "🏖️" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "Ganaste", t: "BONUS", a: 2000, d: "Suma $2,000 a tu ingreso pasivo.", i: "🏆" },
    { n: "Casino", t: "DADO_EVENTO", d: "Paga $1,000 y pierde 1 de felicidad por punto.", i: "🎰" },
    { n: "Bienestar Integral", t: "ENTRADA", r: "BIENESTAR", d: "Entra a la ruta de Bienestar", i: "🧘" },
    { n: "Reto", t: "CARTA", c: "RETO", d: "Toma una carta de 'Oportunidad'", i: "⚡" },
    { n: "Recita un Poema", t: "BONUS", a: 0, d: "Si te aplauden, todos ganan +3 felicidad O +3 salud.", i: "📜" },
    { n: "Impacto Creativo", t: "ENTRADA", r: "IMPACTO", d: "Entra a la ruta de Impacto Creativo", i: "🎨" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "Relax", t: "RELAX", d: "No pasa nada. Relájate.", i: "😌" },
    { n: "HOSPITAL", t: "ESQUINA", d: "Tira dado: Paga $1,000 por punto y gana 1 Salud por punto.", i: "🏥" },
    { n: "Familia", t: "DADO_EVENTO", d: "Convives en familia. Tira dado: Ganas $1,000 y 1 Salud por punto.", i: "👨‍👩‍👧" },
    { n: "Reto", t: "CARTA", c: "RETO", d: "Toma una carta de 'Oportunidad'", i: "⚡" },
    { n: "Impuestos", t: "DADO_EVENTO", d: "Tira 1 dado: Paga $1,000 x punto.", i: "💸" },
    { n: "Liderazgo Mentoría", t: "ENTRADA", r: "LIDERAZGO", d: "Entra a la ruta de Liderazgo", i: "👑" },
    { n: "Alerta Pandemia", t: "DADO_EVENTO", d: "Virus nuevo. Tira dado: Pierde 1 Salud x punto.", i: "🦠" },
    { n: "Expertis", t: "CARTA", c: "EXPERTIS", d: "Toma una carta de 'Expertis'", i: "🧠" },
    { n: "Libertad Financiera", t: "ENTRADA", r: "LIBERTAD", d: "Entra a la ruta de Libertad Financiera", i: "🏝️" },
    { n: "Reto", t: "CARTA", c: "RETO", d: "Toma una carta de 'Oportunidad'", i: "⚡" },
    { n: "Feliz Cumpleaños", t: "BONUS", a: 1000, d: "Todos los jugadores te regalan $1,000.", i: "🎂" },
];